Issue#1
DataInMotion/avatar-dataspace pull request #3
Opened 2024-11-27 12:04 UTC by isalvadori

+ Added component which generates 10 fake `Patient` into db, if no other `Patient` is found.
+ Used `net.datafaker` for generating fake data --> needed re-bundled (we need to put this into a dedicated repo for osgified libraries)

2024-11-27 13:34 UTC, maho7791 commented on net.datafaker/bnd.bnd
> +Export-Package: *
Look to export something like net.* instead of just *.
* can cause also export transient dependencies

2024-11-27 13:35 UTC, maho7791 commented on net.datafaker/resources/_AL.yml
Include resource from the jar like this:

https://github.com/geckoprojects-org/org.gecko.playground/blob/a214af859cbac6bec29a4b6aaaaacc5103b23e27/org.gecko.playground.lucene/bnd.bnd#L8

2024-11-27 13:36 UTC, maho7791 requested changes
Please see my comments ...

2024-11-28 07:28 UTC, isalvadori commented on net.datafaker/resources/_AL.yml
This doesn't help, in the sense that the yml files are not taken into account this way. I had to do something like this to make it work 
```
=@${repo;net.datafaker:datafaker:jar:sources;${lib.version};EXACT}
```

2024-12-03 08:03 UTC, closed without merging